# Generated by Django 5.2.4 on 2025-07-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='date',
            new_name='date_start',
        ),
    ]
