# Generated by Django 5.2.4 on 2025-07-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_date_tournament_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
