# Generated by Django 5.2.4 on 2025-07-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_tournament_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-date_start'], 'permissions': [('can_manage_tournament', 'Can manage tournament')]},
        ),
        migrations.AlterModelOptions(
            name='tournamentparticipant',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AlterField(
            model_name='player',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='twitch',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=True, help_text='Torneio visível para todos os usuários.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='server_discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participants', to='players.tournament'),
        ),
    ]
