# Generated by Django 5.2.4 on 2025-07-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipant',
            old_name='player',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='participating_tournaments', through='players.TournamentParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_info', to='players.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
    ]
